[package]
name = "codegen_test_subpro"
version = "0.1.0"
edition = "2024"

[dependencies]
handlebars = "4.3"
chrono = "0.4"
serde_json = "1.0"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }