[package]
name = "aadl_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
pest = "2.8"
pest_derive = "2.8"
pest_debugger = "2.8"

prettyprint = "0.8"

syn = { version = "2.0", features = ["full", "extra-traits"] }
quote = "1.0"
prettyplease = "0.2"

proc-macro2 = "1.0"

chrono = "0.4" 
